// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreDAL.Data;

#nullable disable

namespace StoreDAL.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("StoreDAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("StoreDAL.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_time");

                    b.Property<int>("OrderStateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_state_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderStateId");

                    b.ToTable("customer_orders");
                });

            modelBuilder.Entity("StoreDAL.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer_name");

                    b.HasKey("Id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("StoreDAL.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CustomerOrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_amount");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("customer_order_details");
                });

            modelBuilder.Entity("StoreDAL.Entities.OrderState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("state_name");

                    b.HasKey("Id");

                    b.ToTable("order_states");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StateName = "New Order"
                        },
                        new
                        {
                            Id = 2,
                            StateName = "Canceled by user"
                        },
                        new
                        {
                            Id = 3,
                            StateName = "Canceled by administrator"
                        },
                        new
                        {
                            Id = 4,
                            StateName = "Confirmed"
                        },
                        new
                        {
                            Id = 5,
                            StateName = "Moved to delivery company"
                        },
                        new
                        {
                            Id = 6,
                            StateName = "In delivery"
                        },
                        new
                        {
                            Id = 7,
                            StateName = "Delivered to client"
                        },
                        new
                        {
                            Id = 8,
                            StateName = "Delivery aproved by client"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("ProductTitleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_title_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ProductTitleId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("StoreDAL.Entities.ProductTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("product_titles");
                });

            modelBuilder.Entity("StoreDAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_role_id");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("StoreDAL.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("UserRoleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_role_name");

                    b.HasKey("Id");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserRoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            UserRoleName = "Registered"
                        },
                        new
                        {
                            Id = 3,
                            UserRoleName = "Guest"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.CustomerOrder", b =>
                {
                    b.HasOne("StoreDAL.Entities.User", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.OrderState", "OrderState")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("OrderStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderState");
                });

            modelBuilder.Entity("StoreDAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("StoreDAL.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany("CustomerOrderDetails")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.Product", "Product")
                        .WithMany("CustomerOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreDAL.Entities.Product", b =>
                {
                    b.HasOne("StoreDAL.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.ProductTitle", "ProductTitle")
                        .WithMany("Products")
                        .HasForeignKey("ProductTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("ProductTitle");
                });

            modelBuilder.Entity("StoreDAL.Entities.ProductTitle", b =>
                {
                    b.HasOne("StoreDAL.Entities.Category", "Category")
                        .WithMany("ProductTitles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StoreDAL.Entities.User", b =>
                {
                    b.HasOne("StoreDAL.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("StoreDAL.Entities.Category", b =>
                {
                    b.Navigation("ProductTitles");
                });

            modelBuilder.Entity("StoreDAL.Entities.CustomerOrder", b =>
                {
                    b.Navigation("CustomerOrderDetails");
                });

            modelBuilder.Entity("StoreDAL.Entities.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreDAL.Entities.OrderState", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("StoreDAL.Entities.Product", b =>
                {
                    b.Navigation("CustomerOrderDetails");
                });

            modelBuilder.Entity("StoreDAL.Entities.ProductTitle", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreDAL.Entities.User", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("StoreDAL.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
